---
ansible_host: "192.168.200.12"
hostname: "leaf02"
post_login_message: |
                #####################################################################################
                #                     You are successfully logged in to: leaf02                     #
                #####################################################################################
eth0_ip: "192.168.200.12/24"
lo_ip: "10.10.10.2/32"
mlag_mac: "44:38:39:BE:EF:AA"
mlag_backup: "10.10.10.1"
vlan_config:
  - { id: 'vlan10', ip: '10.1.10.3/24', vlan: '10'}
bgp_asn: '65102'
bgp_routerid: '10.10.10.2'
