---
- name: Set bridge
  bridge:
    state: merged
    revid: '{{ revision.revid }}'
    data:
      - id: 'br_default'
        untagged: 1
        type: 'vlan-aware'
        vlan:
          - id: '10'
            vni:
              - id: '10'