---
stages:
  - test

sanity:
  stage: test
  image: python:3.9
  before_script:
    - apt update && apt install rsync -y
    - python3 -m pip install ansible
    - mkdir ansible_collections
    - ansible-galaxy collection install ansible.netcommon -p ansible_collections/
  script:
    - make test
  artifacts:
    expire_in: 1 week

ansible-lint:
  stage: test
  before_script:
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - git submodule update --init
    - pip install --upgrade ansible ansible-lint
    - ansible --version
    - ansible-lint --version
  script:
    - ansible-lint ~/.ansible/collections/ansible_collections/nvidia/nvue/examples/playbooks/*.yml
  artifacts:
    expire_in: 1 week