---
stages:
  - test

sanity:
  stage: test
  image: python:3.9
  before_script:
    - apt update && apt install rsync -y
    - python3 -m pip install ansible
    - ansible-galaxy collection install ansible.netcommon
  script:
    - make test-ci
  artifacts:
    expire_in: 1 week
