---
stages:
  - test

sanity:
  stage: test
  image: python:3.9
  before_script:
    - apt update && apt install rsync -y
    - python3 -m pip install ansible
    - mkdir ansible_collections
    - ansible-galaxy collection install ansible.netcommon -p ansible_collections/
  script:
    - make test
  artifacts:
    expire_in: 1 week
