---
stages:
  - test

sanity:
  stage: test
  image: python:3.9
  variables:
    COLLECTIONS_PATHS: ./
  before_script:
    - python3 -m pip install ansible
    - mkdir -p ansible_collections/nvidia
    - ln -s $(pwd) ansible_collections/nvidia/nvue
  script:
    - ansible-test sanity
  artifacts:
    expire_in: 1 week
