---
stages:
  - test

sanity:
  stage: test
  image: python:3.9
  variables:
    COLLECTIONS_PATHS: ./
  before_script:
    - python3 -m pip install ansible
    - mkdir -p ansible_collections/nvidia/nvue
    - cp -r galaxy.yml plugins tests ./ansible_collections/nvidia/nvue
  script:
    - cd ./ansible_collections/nvidia/nvue/
    - ansible-test sanity
  artifacts:
    expire_in: 1 week
