---
stages:
  - test

sanity:
  stage: test
  image: python:3.9
  variables:
    GIT_CLONE_PATH: ~/.ansible/collections/ansible_collections/nvidia/nvue
  GIT_CLONE_PATH
  before_script:
    - python3 -m pip install ansible
  script:
    - ansible-test sanity
  artifacts:
    expire_in: 1 week
