---

- name: Test playbook to setup system config on leaf switches
  hosts: leafs
  connection: ansible.netcommon.httpapi
  gather_facts: false
  vars:
    ansible_network_os: nvidia.nvue.httpapi
    ansible_httpapi_port: 8765
    ansible_httpapi_use_ssl: true
    ansible_httpapi_validate_certs: false

  tasks:
    - name: Create new revision
      nvidia.nvue.config:
        state: new
      register: revision

    - name: dump revision
      debug:
        msg: '{{ revision.revid }}'

    - name: Set system settings
      ansible.builtin.include_role: 
        name: system