objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  httpapi:
    httpapi:
      description: httpapi plugin for NVIDIA's NVUE API
      name: httpapi
      version_added: null
  inventory: {}
  lookup: {}
  module:
    api:
      description: Use httpapi to run command on NVUE devices
      name: api
      namespace: ''
      version_added: null
    command:
      description: Run NVUE commands on Nvidia Cumulus Linux
      name: command
      namespace: ''
      version_added: null
  netconf: {}
  shell: {}
  strategy: {}
  vars: {}
version: 1.0.0
