---
- name: Set system settings
  nvidia.nvue.system:
    state: merged
    revid: '{{ revision.revid }}'
    data:
      hostname: '{{ hostname }}'
      timezone: '{{ timezone }}'
      login_message:
        post_login: '{{ post_login_message }}'
        pre_login: '{{ pre_login_message }}'
