---
- name: Set system settings
  nvidia.nvue.system:
    state: merged
    revid: '{{ revision.revid }}'
    data:
      hostname: {{ hostname }}
      timezone: 'Etc/UTC'
      message:
        post_login: |
                  #####################################################################################
                  #                     You are successfully logged in to: {{ hostname }}                     #
                  #####################################################################################
        pre_login: |
                  #####################################################################################
                  #  Welcome to NVIDIA Cumulus VX (TM) 5.6                                            #
                  #  NVIDIA Cumulus VX (TM) is a community supported virtual appliance designed       #
                  #  for experiencing, testing and prototyping NVIDIA Cumulus'"'"' latest technology. #
                  #  For any questions or technical support, visit our community site at:             #
                  #  https://www.nvidia.com/en-us/support                                             #
                  #####################################################################################
