---
pre_login_message: |
                #####################################################################################
                #  Welcome to NVIDIA Cumulus VX (TM) 5.8                                            #
                #  NVIDIA Cumulus VX (TM) is a community supported virtual appliance designed       #
                #  for experiencing, testing and prototyping NVIDIA Cumulus'"'"' latest technology. #
                #  For any questions or technical support, visit our community site at:             #
                #  https://www.nvidia.com/en-us/support                                             #
                #####################################################################################
interfaces_up: 
  - "swp49"
  - "swp50"
  - "swp51"
  - "swp1"
bond_config:
  - { id: 'bond1', mlagid: 1, member: 'swp1', bridge: 'br_default'}
bgp_neighbors: 
  - "swp51"
  - "swp52"